name: Sync to CampoInteligente

on:
<<<<<<< HEAD
  push: # Gatilho para executar ao receber commits
    branches:
      - main # Executa apenas se o push for na branch main
=======
  push:                     # Gatilho para executar ao receber commits
    branches:
      - main                # Executa apenas se o push for na branch main
>>>>>>> da857ce27443cd0e6381c970293c119e235fa0ce
  schedule:
    - cron: "*/30 * * * *" # Executa a cada 30 minutos
  workflow_dispatch: # Permite execução manual

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "Marcos Morais"
          git config --global user.email "marcosmoraisjr@users.noreply.github.com"

      - name: Clonar repositório de origem
        run: |
          git clone https://marcosmoraisjr:${{ secrets.GH_PAT }}@github.com/restic36/startup-campo-inteligente-site.git source
          cd source
          git remote add destino https://marcosmoraisjr:${{ secrets.GH_PAT }}@github.com/marcosmoraisjr/CampoInteligente.git
          git push --force destino main
