name: update-readme

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  push:
    branches:
      - main # Executa ao detectar alterações
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Executar script Python
        run: |
          cd documentos
          python update-readme.py

      - name: Verificar alterações
        run: git status    

      - name: Commit e Push
        run: |
          git add -u
          git diff --quiet || git commit -m "Atualização automática do README"
          git push origin main
        env: 
          GH_PAT: ${{ secrets.GH_PAT }}
