name: update-readme

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  push:
    branches:
      - main # Executa ao detectar alterações
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Executar script Python
        run: python update-readme.py

      - name: Commit e Push
        run: |
          git add documentos/README.md  # Especificando o caminho correto do arquivo
          git commit -m "Atualização automática do README"
          git push https://$GH_PAT@github.com/restic36/startup-campo-inteligente-site.git

        env:
          GH_PAT: ${{ secrets.GH_PAT }}
