name: update-readme

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  push:
    branches:
      - main # Executa ao detectar alterações
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Executar script Python
        run: |
          cd documentos
          python update-readme.py

      - name: Commit e Push
        run: |
          git add documentos/README.md documentos/versao.txt
          git commit -m "Atualização automática do README" || echo "Nenhuma alteração para commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
